src/main/java/hudson/scm/subversion/UpdateUpdater.java

The UpdateUpdater.perform will throw an AbortException now, as suggested in [this issue description](https://issues.jenkins-ci.org/browse/JENKINS-26264)

[FIXED JENKINS-26264] UpdateUpdater perform will throw an AbortException

---

src/main/java/hudson/scm/SubversionSCM.java

The `SubversionSCM.getRevisionFile(AbstractBuild)` was altered to use instead `Run`, however some plugins have not converted to using the `Run` class, so I am restoring the method and deprecating it.
@reviewbybees

[FIXED JENKINS-26611] Restore getRevisionFile(AbstractBuild) method.

---

src/main/resources/hudson/scm/SubversionTagAction/tagForm.jelly

Not sure exactly when the `tagForm` view is being used, but if it is ever used from a Workflow build (or any other non-`AbstractBuild`), this patch would be needed in order to refer to the build.
@reviewbybees

AbstractScmTagAction.getBuild is deprecated in favor of getRun

---

src/main/java/hudson/scm/PerJobCredentialStore.java
src/main/java/hudson/scm/SubversionSCM.java

https://issues.jenkins-ci.org/browse/JENKINS-29211
This pull request tries to improve the migration process that the plugin implements for upgrading repositories with an old credentials format.
Result after upgrading:
We lose the relation between our repository and the credentials.

[JENKINS-29211] E200015: ISVNAuthentication provider did not provide credentials

---

src/main/java/hudson/scm/SubversionSCM.java
src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java

While working on Subversion-based integration tests for https://github.com/jenkinsci/workflow-plugin/pull/147 I found that branch indexing would fail with the following error:
```
Indexing started at …
Started
Opening conection to file:///…reporoot/
FATAL: Failed to index
java.lang.NullPointerException
at hudson.scm.SubversionSCM$DescriptorImpl.getRelativePath(SubversionSCM.java:2375)
at jenkins.scm.impl.subversion.SubversionSCMSource.retrieve(SubversionSCMSource.java:218)
at jenkins.scm.api.SCMSource.fetch(SCMSource.java:141)
at jenkins.branch.MultiBranchProject.populateBranchItemsFromSCM(MultiBranchProject.java:727)
at jenkins.branch.MultiBranchProject.access$500(MultiBranchProject.java:160)
at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1873)
at …
```

SVNRepository.getRepositoryRoot(false) can return null

---

src/main/java/hudson/scm/SubversionWorkspaceSelector.java
src/main/java/hudson/scm/subversion/CheckoutUpdater.java
src/test/java/hudson/scm/SVNWorkingCopyTest.java

https://issues.jenkins-ci.org/browse/JENKINS-26458
There are several plugins which are using an older version of the svnkit library which still use the workspace format of `100`. Since previous versions of this plugin used 100 as the workspace format this will guard against only an invalid format of `100`.

[JENKINS-26458] Guard against a workspace format of 100.

---

src/main/java/hudson/scm/RevisionParameterAction.java
src/main/java/hudson/scm/SubversionChangeLogBuilder.java

https://issues.jenkins-ci.org/browse/JENKINS-29492
Fixing several findbugs issues:
* Use `%n` instead of `\n` to handle platform-specific line separators.
* Use `StringBuilder` for concatenating strings.
* Unnecessary unboxing of longs.
* Ignore the debugging static variable which can be mutable.
@reviewbybees

[JENKINS-29492] Fix some findbugs issues

---

pom.xml
src/main/java/hudson/scm/SubversionSCM.java
src/main/java/hudson/scm/subversion/UpdaterException.java

In this PR is included:
* Javadoc Maven Plugin configured
* Some Javadoc warning solved 
* And additionally, Surefire Maven Plugin moved to `plugins` section.
Now, it is possible to cut a release using JDK8. Javadocs (by default, in JDK8) is very strict.
@reviewbybees

[JENKINS-30050] Stuff related to Javadoc

---

src/main/java/hudson/scm/SubversionSCM.java

https://issues.jenkins-ci.org/browse/JENKINS-30197
During some migrations from 1.x to 2.5.1, I've seen the following stack trace:
```
SEVERE: Failed SubversionSCM.perJobCredentialsMigration
java.lang.Error: java.lang.reflect.InvocationTargetException
at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:109)
at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:169)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
at jenkins.model.Jenkins$7.runTask(Jenkins.java:903)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at …
```

[JENKINS-30197] ClassCastException when migrating credentials

---

src/main/java/hudson/scm/subversion/UpdateUpdater.java

Cleanup `AbortException` call by removing unnecessary part. See comment https://github.com/jenkinsci/subversion-plugin/pull/106#discussion_r23236498.
@reviewbybees

[JENKINS-26264] Cleanup AbortException call.

---

src/main/java/hudson/scm/SubversionRepositoryStatus.java
src/test/java/hudson/scm/SubversionRepositoryStatusTest.java

Corrected issue explained in https://issues.jenkins-ci.org/browse/JENKINS-24802
Refactored SubversionRepositoryStatus to make onNotify method shorter and more "understandable"
Added unit tests for one refactored method

[FIXED JENKINS-24802] - notifyCommit don't trigger a build if two svn repositories have same URL start

---

pom.xml
src/main/java/hudson/scm/CredentialsSVNAuthenticationProviderImpl.java
src/main/java/hudson/scm/SubversionSCM.java

[JENKINS-31192](https://issues.jenkins-ci.org/browse/JENKINS-31192)
Take benefits of new SVNKit 1.8.11 SVNSSLAuthentication methods to properly support byte array PKCS#12 certificate usage.

[JENKINS-31192] Fix HTTPS SSL client certificate authentication

---

src/main/java/hudson/scm/SubversionRepositoryStatus.java

[JENKINS-31385](https://issues.jenkins-ci.org/browse/JENKINS-31385)
If `svn:externals` is used and the user has not configured *Additional Credentials* then `SVNCancelException` is thrown. A lot of times subversion users don't know they need to configure the external credentials on `Additional Credentials` section, so it might be a good idea to catch this exception and provide some user-friendly information.
@reviewbybees @recena @christ66

[FIXED JENKINS-31385] Additional logs when using svn:externals is used and SVNCancelException is thrown

---

src/main/java/hudson/scm/SubversionSCM.java
src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java

[JENKINS-16711](https://issues.jenkins-ci.org/browse/JENKINS-16711)
This PR is the second part of https://github.com/jenkinsci/subversion-plugin/pull/149
Examples:
* [https://subversion.assembla.com/svn/jenkins-31937-2/project1/User Guide/](https://subversion.assembla.com/svn/jenkins-31937-2/project1/User Guide/)
* [https://subversion.assembla.com/svn/my repo/project1/User Guide/](https://subversion.assembla.com/svn/my repo/project1/User Guide/)
@reviewbybees

[JENKINS-16711] SVNPath must be built from a decoded path

---

src/main/java/hudson/scm/SubversionChangeLogBuilder.java
src/main/java/hudson/scm/SubversionEventHandlerImpl.java

We want to avoid this:
@reviewbybees

[JENKINS-16711] Encode the URLs when are shown in the logger

---

src/main/java/hudson/scm/listtagsparameter/ListSubversionTagsParameterValue.java

[JENKINS-27718](https://issues.jenkins-ci.org/browse/JENKINS-27718)
ParameterValue.buildEnvVars() was deprecated in Jenkins 1.344.
See:
http://javadoc.jenkins-ci.org/hudson/model/ParameterValue.html#buildEnvVars%28hudson.model.AbstractBuild,%20java.util.Map%29
and also see:
https://github.com/jenkinsci/jenkins/commit/d1b713a4d86a846af2305705e42de8f0709b19ce
This fix is needed for the workflow plugin.

[JENKINS-27718] Override ParameterValue.buildEnvironment()

---

src/main/java/hudson/scm/SubversionSCM.java

..when one uses `svn://` and `file://` protocols.
[JENKINS-32169](https://issues.jenkins-ci.org/browse/JENKINS-32169)
PR related: https://github.com/jenkinsci/subversion-plugin/pull/129
@reviewbybees , esp @jglick

[JENKINS-32169] SVNRepository.getRepositoryRoot(false) can return null

---

pom.xml
src/main/resources/hudson/scm/SubversionChangeLogSet/digest.jelly
src/main/resources/hudson/scm/SubversionChangeLogSet/index.jelly
src/main/resources/hudson/scm/SubversionMailAddressResolverImpl/global.jelly
src/main/resources/hudson/scm/SubversionSCM/AdditionalCredentials/config.jelly
src/main/resources/hudson/scm/SubversionSCM/DescriptorImpl/credentialOK.jelly
src/main/resources/hudson/scm/SubversionSCM/DescriptorImpl/enterCredential.jelly
src/main/resources/hudson/scm/SubversionSCM/DescriptorImpl/url-help.jelly
src/main/resources/hudson/scm/SubversionSCM/ModuleLocation/config.jelly
src/main/resources/hudson/scm/SubversionSCM/config.jelly
src/main/resources/hudson/scm/SubversionSCM/global.jelly
src/main/resources/hudson/scm/SubversionTagAction/tagForm.jelly
src/main/resources/hudson/scm/browsers/AbstractSventon/config.jelly
src/main/resources/hudson/scm/browsers/Assembla/config.jelly
src/main/resources/hudson/scm/browsers/CollabNetSVN/config.jelly
src/main/resources/hudson/scm/browsers/FishEyeSVN/config.jelly
src/main/resources/hudson/scm/browsers/SVNWeb/config.jelly
src/main/resources/hudson/scm/browsers/ViewSVN/config.jelly
src/main/resources/hudson/scm/browsers/WebSVN/config.jelly
src/main/resources/hudson/scm/listtagsparameter/ListSubversionTagsParameterDefinition/config.jelly
src/main/resources/hudson/scm/listtagsparameter/ListSubversionTagsParameterDefinition/index.jelly
src/main/resources/hudson/scm/listtagsparameter/ListSubversionTagsParameterValue/value.jelly
src/main/resources/hudson/scm/subversion/CheckoutUpdater/config.jelly
src/main/resources/hudson/scm/subversion/UpdateUpdater/config.jelly
src/main/resources/hudson/scm/subversion/UpdateWithCleanUpdater/config.jelly
src/main/resources/hudson/scm/subversion/UpdateWithRevertUpdater/config.jelly
src/main/resources/hudson/scm/subversion/WorkspaceUpdater/config.jelly
src/main/resources/hudson/scm/subversion/enterCredential.jelly
src/main/resources/jenkins/scm/impl/subversion/SubversionSCMSource/config-detail.jelly

[JENKINS-32747](https://issues.jenkins-ci.org/browse/JENKINS-32747)
As part of this PR these tests should be solved:
```
hudson/scm/SubversionSCM/DescriptorImpl/url-help.jelly(org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: <?jelly escape-by-default='true'?> is missing
at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck.runTest(JellyTestSuiteBuilder.java:98)
```
@reviewbybees

[JENKINS-32747] Adapt to Plugin POM 2.3

---

pom.xml

SVNKit 1.8.14, released 10 Oct 2016, provides [a number of bug fixes](https://svn.svnkit.com/repos/svnkit/tags/1.8.14/CHANGES.txt).
It also addresses [SVNKIT-672](https://issues.tmatesoft.com/issue/SVNKIT-672), vastly improving performance on 32-bit Linux.

Upgrade to svnkit 1.8.14.

---

src/main/resources/hudson/scm/SubversionChangeLogSet/digest.jelly
src/main/resources/hudson/scm/SubversionChangeLogSet/index.jelly

Commit decorators add clicable <a> links to issue IDs on build summary page,
but the security mechanism preventing XSS in .jelly,
escapes the HTML tags for .jelly files with:
jelly escape-by-default='true'
After the change, annotated commit messages are printed raw,
without HTML escaping.
Used method will be consistent with change in hudson/scm/SCM/project-changes.jelly
introduced in https://github.com/jenkinsci/jenkins/commit/41ab84fe0a1512fe52347d55fb58445174636896
Additional details:
https://wiki.jenkins-ci.org/display/JENKINS/Jelly+and+XSS+prevention
https://issues.jenkins-ci.org/browse/JENKINS-5135

[JENKINS-36521] Print raw (not HTML escaped) commit messages

---

pom.xml

Jenkins plugins should specify the Jenkins repository to make sure they can be built without a custom `~/.m2/settings.xml`, so part of #172 was wrong. (Inheriting `distributionManagement` is correct.)
#170 was not wrong, but the original use of a custom repository here was. Fixed by manually uploading the [third-party library in question](https://repo.jenkins-ci.org/releases/com/trilead/trilead-ssh2/1.0.0-build221/). That also allows other plugins to compile against `subversion` 2.7.1 without hassle.
@reviewbybees esp. @recena, @daniel-beck

Fixing repository declarations

---

src/main/java/hudson/scm/SubversionSCM.java

It looks like there was some sort of credentials management within this plugin before the credentials api was introduced. Some of that code is still on hot paths and caused the NPE reported in [JENKINS-32302](https://issues.jenkins-ci.org/browse/JENKINS-32302). @stephenc this is an oldie of yours I think. I wonder if its safe just to remove all that migration code and the old credentials impl?
@reviewbybees

JENKINS-32302 dead code before Credentials API causes NPE

---

src/main/java/hudson/scm/listtagsparameter/ListSubversionTagsParameterDefinition.java
src/main/java/jenkins/scm/impl/subversion/SVNRepositoryView.java
src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
src/test/java/hudson/scm/SubversionSCMTest.java

[JENKINS-42186](https://issues.jenkins-ci.org/browse/JENKINS-42186)
A quick scan of the source code shows that we don't properly clean up instances of `SVNRepository` like we should.
What seems to be happening is that we are creating `SVNRepositoryView` over and over in `retrieve` and not closing it. When this occurs, we end up with many instances of `SVNRepositoryView` open which has file descriptors open to a on disk cache (created by `DBMaker.newFileDB`). This is what eats all the file handles and causes havoc. 
PTAL @recena @jglick 
@reviewbybees

JENKINS-42186 Fix some potential file leaks

---

src/main/java/hudson/scm/SubversionChangeLogSet.java

The issue is generally described in JIRA https://issues.jenkins-ci.org/browse/JENKINS-44076 along with the motivation and description of this proposed fix.
I have not been able to sensibly stub the execution context for the SubversionChangeLogSet.LogEntry.preparePath(String) method to create a relevant unit test for this change.

[JENKINS-44076] : hudson.scm.SubversionChangeLogSet.LogEntry.getAffectedPaths() does not provide expected result for parametrized Repository URLs

---

src/main/java/hudson/scm/SubversionSCM.java

Not a huge issue, just something I noticed while using the plugin.

Fix grammatical error on SVN access exception

---

src/main/resources/hudson/scm/SubversionChangeLogSet/digest.jelly

As suggested in https://issues.jenkins-ci.org/browse/JENKINS-22112
Show commiter name on build status page
@daniel-beck was wondering whether this should be shown stating that it's supposed to be a short + succinct summary of changes
I will leave the final decision to the community.
Here is the before and after:
<b>Before:</b> http://imgur.com/mEYuGgq,taNVqUL
<b>After:</b> http://imgur.com/mEYuGgq,taNVqUL#1

[FIXED JENKINS-22112] Show commiter name on build status page

---

src/main/resources/hudson/scm/SubversionSCM/AdditionalCredentials/help-realm.html
src/main/resources/hudson/scm/SubversionSCM/help-additionalCredentials.html

In its current form, the Jenkins Subversion plugin does not indicate the correct realm name to use for repositories accessed using the **svn+ssh://** protocol. This commit is intended to fix this, as I spent 3 days trying to work out how to run a Jenkins job where one repository had an svn:external pointing to an **svn+ssh://** repository, and I don't want anyone else to have the same problem!

Change the Additional Credentials help to give correct realm name for svn+ssh repositories

---

pom.xml
src/test/java/hudson/scm/AbstractSubversionTest.java
src/test/java/hudson/scm/CredentialsExternalsTest.java
src/test/java/hudson/scm/DefaultSVNLogFilterTest.java
src/test/java/hudson/scm/PerJobCredentialStoreTest.java
src/test/java/hudson/scm/SVNWorkingCopyTest.java
src/test/java/hudson/scm/SubversionChangeLogParserTest.java
src/test/java/hudson/scm/SubversionSCMTest.java
src/test/java/hudson/scm/listtagsparameter/ListSubversionTagsParameterDefinitionTest.java
src/test/java/jenkins/scm/impl/subversion/SubversionSampleRepoRule.java

Amends #194 which was merged prematurely. Subsumes #193. Quick fix to get builds passing. Better would be to improve tests to run portably, as mentioned in comments.
@reviewbybees

Skip tests on CI when Subversion is not installed locally

---

src/main/java/hudson/scm/listtagsparameter/ListSubversionTagsParameterDefinition.java

@jglick, @oleg-nenashev
This PR fixes the memory leak reported in JENKINS-15376. It is based on #162 but with the merge conflict resolved. (I.e. it is similar to #166). When this PR gets merged both can be closed.
All credits go to @2improveIT and @hplatou who already came up with a fix for this.
Without this fix our Jenkins runs out of memory every 2 or 3 days. It would be nice to see this merged so other people can benefit from it as well.

Fix memory leak (JENKINS-15376)

---

src/main/java/hudson/scm/listtagsparameter/ListSubversionTagsParameterDefinition.java

When using the jenkins-cli to build a job with a tag parameter a error message occurred.
The following minor change solves this. Basically I looked how this was solved for the GET/POST handling and transformed it to make it work.

Fixed that subversion tag parameter could not be used in CLI.

---

src/main/java/hudson/scm/SubversionEventHandlerImpl.java
src/main/java/hudson/scm/SubversionSCM.java
src/main/java/hudson/scm/subversion/CheckoutUpdater.java
src/main/java/hudson/scm/subversion/SubversionUpdateEventHandler.java
src/main/java/hudson/scm/subversion/UpdateUpdater.java
src/main/java/hudson/scm/subversion/WorkspaceUpdater.java
src/main/resources/hudson/scm/SubversionSCM/config.jelly
src/main/resources/hudson/scm/SubversionSCM/help-quietOperation.html
src/main/resources/hudson/scm/SubversionSCM/help-quietOperation_zh_TW.html
src/test/java/hudson/scm/SubversionSCMTest.java

Adds an option in Subversion scm config to reduce significant amount of logs produced during build when checking out / updating working copy.
Includes both English and traditional Chinese help files / descriptions.
Also added a unit test for this feature.
https://issues.jenkins-ci.org/browse/JENKINS-14541
CC @recena, @jglick, @oleg-nenashev, @TomaszHal 
See https://github.com/jenkinsci/subversion-plugin/pull/136

[JENKINS-14541] --quiet mode for svn checkout / update

---

src/main/java/jenkins/scm/impl/subversion/SVNRepositoryView.java

Previous code caught two specific checked exceptions and closed the repository session only for those. But RuntimeException could occur as well, so the new pattern will work in all cases where success did not occur.

Repository session was not closed for unexpected exceptions

---

src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java

This is similar to JENKINS-44271, applies the same fix that was applied to the git plugin for that issue. I also found a conflict with passing the parameter to a couple other functions that didn't appear to make use of them.  As best as I can tell, nothing is using these functions so I think removing the unused parameter should be ok.

[JENKINS-49624] Fix selecting credentials for Pipeline Libraries using Modern SCM

---

src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java

This is based on comments in the JIRA issue and some additional investigation.  I think I have the interaction with the `SCMHeadObserver` working correctly.
In the diagram in the JIRA issue, the directory containing Jenkinsfile is at an older revision than the root directory of the scan.  This results in subversion not resolving the path since a directory in the middle of the path tree didn't exist in that specific revision.  The simple fix it so just always scan using HEAD, however that means that any notifications to the `SCMHeadObserver` wouldn't contain a valid revision.  This fix scans using HEAD, and then once it finds the Jenkinsfile checks if the specific revision would have worked.  If it did, then it assumes that it needs to notify the observer using that revision.  If the final …

[JENKINS-41626] Fix path detection when subfolder older than root folder

---

src/main/java/hudson/scm/SubversionSCM.java
src/main/java/hudson/scm/subversion/CheckoutUpdater.java
src/main/java/hudson/scm/subversion/SubversionUpdateEventHandler.java
src/main/java/hudson/scm/subversion/UpdateUpdater.java
src/main/resources/hudson/scm/SubversionSCM/ModuleLocation/config.jelly
src/main/resources/hudson/scm/SubversionSCM/ModuleLocation/help-cancelProcessOnExternalsFail.html

which determines if the process should be cancelled when checkout/update svn:externals failed.
Sometimes, when svn:externals checkout/update failed, the artifacts generated is likely to fall short of expectations, but now it's ignored by default and no message can found in the log.

Add new option "cancelProcessOnExternalsFail" for ModuleLocation

---

src/main/java/hudson/scm/SubversionSCM.java
src/main/java/hudson/scm/subversion/CheckoutUpdater.java
src/main/java/hudson/scm/subversion/UpdateUpdater.java
src/main/java/hudson/scm/subversion/UpdateWithRevertUpdater.java
src/main/java/hudson/scm/subversion/WorkspaceUpdater.java

SVNKit checks out to infinity by default if unknown is given as the
depth to checkout. If you're using as-it-is you probably don't want the
whole source tree, so change as-it-is to set the depth to files for
checkout and unknown for updates.
Not sure how flexible to be here some people might really want immediates or empty instead of files. But files is probably close enough isn't it. There could be an extra setting for this but I don't think that necessary.

Make as-it-is checkout only files initally

---

Jenkinsfile
pom.xml
src/main/java/hudson/scm/CredentialsSVNAuthenticationProviderImpl.java
src/main/java/hudson/scm/DirAwareSVNXMLLogHandler.java
src/main/java/hudson/scm/SubversionEventHandlerImpl.java
src/main/java/hudson/scm/SubversionSCM.java
src/main/java/hudson/scm/subversion/SubversionUpdateEventHandler.java
src/main/java/hudson/scm/subversion/UpdateWithCleanUpdater.java
src/main/java/jenkins/scm/impl/subversion/RemotableSVNErrorMessage.java
src/main/resources/META-INF/hudson.remoting.ClassFilter
src/test/java/hudson/scm/SubversionSCMTest.java
src/test/java/jenkins/scm/impl/subversion/RemotableSVNErrorMessageStepTest.java

Maybe RemotableSVNErrorMessage should check whether the constructor runs on the master and use ProxyException only on the agent side.
https://issues.jenkins-ci.org/browse/JENKINS-50339

[JENKINS-50339] - Whitelist SVNErrorMessage and introduce RemotableSVNErrorMessage

---

pom.xml

It is currently impossible to build because there are lambdas in recent commits that require java 8. We are also using svnkit 1.9.2 without problems and all unit tests pass

java 8 required for presence of lambdas and svnkit to 1.9.2

---

pom.xml
src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java

[JENKINS-50861](https://issues.jenkins-ci.org/browse/JENKINS-50861)
* Update Pipeline SCM step to 2.3
* Update Pipeline to 2.5 for test
* Update core to 2.60
* Update Java to 8
* Update SCM API  to 2.2.6
* Update credentials to 2.1.16
* fix inherited dependencies
* propagate new exceptions
@reviewbybees

[FIX JENKINS-50861] update core and Pipeline scm step dependencies

---

src/main/java/hudson/scm/SubversionWorkspaceSelector.java
src/main/java/hudson/scm/subversion/CheckoutUpdater.java

WARNING: Attempt to (de-)serialize anonymous class hudson.scm.subversion.CheckoutUpdater$1
WARNING: Attempt to (de-)serialize anonymous class hudson.scm.SubversionWorkspaceSelector$1
see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
See [JENKINS-50457](https://issues.jenkins-ci.org/browse/JENKINS-50457).

[JENKINS-50457] Convert anonymous classes to members

---

pom.xml

[JENKINS-53325](https://issues.jenkins-ci.org/browse/JENKINS-53325)
* Exclude trilead-ssh2 dependency on svnkit

[JENKINS-53325] Exclude trilead-ssh2 dependency on svnkit

---

pom.xml
src/test/java/hudson/scm/AbstractSubversionTest.java

* Update Jenkins core version to 2.73.3
* Remove <maskClasses>com.trilead.ssh2</maskClasses>
[JENKINS-53325](https://issues.jenkins-ci.org/browse/JENKINS-53325)

[JENKINS-53325] Use trilead classes from Jenkins core

---

src/main/java/hudson/scm/SubversionSCM.java

Jenkins CasC configuration snippet:
```
subversionSCM:
globalExcludedRevprop: 'globalExcludedRevprop'
workspaceFormat: 8
```
`workspaceFormat` to Subversion version mapping:
workspaceFormat | version
-- | --
8 | 1.4
9 | 1.5
10 | 1.6
29 | 1.7
31 | 1.8

Support jenkins configuration as code plugin

---

src/main/java/hudson/scm/DirAwareSVNXMLLogHandler.java
src/main/java/hudson/scm/SubversionChangeLogSet.java
src/main/java/hudson/scm/SubversionSCM.java
src/main/java/hudson/scm/listtagsparameter/ListSubversionTagsParameterValue.java
src/test/java/hudson/scm/DefaultSVNLogFilterTest.java
src/test/java/hudson/scm/SubversionSCMTest.java
src/test/java/jenkins/scm/impl/subversion/SubversionSCMFileSystemTest.java
src/test/java/jenkins/scm/impl/subversion/SubversionSCMSourceTest.java

Just some minor code cleanups:
* removed superfluous semicolons
* Introduced Object equals
* simplified asserts
* removed unneeded throws Exceptions
* replaced * imports

Minor code cleanup

---

pom.xml
src/main/java/hudson/scm/SubversionSCM.java
src/test/java/hudson/scm/SubversionSCMTest.java

[JENKINS-62278](https://issues.jenkins-ci.org/browse/JENKINS-62278)
Users with `Jenkins.MANAGE` should be able to configure global settings.
(`Jenkins.MANAGE` requires a core bump, and I'm also updating the parent).

[JENKINS-62278] Jenkins.MANAGE access global config

---

pom.xml

See [JENKINS-65862](https://issues.jenkins.io/browse/JENKINS-65862)
When `commons-digester3` was added as a dependency, it bundled in `asm` and `common-beanutils`, both of which are included in core. This PR excludes `asm` and `common-beanutils` from `commons-digester3`
upstream of https://github.com/jenkinsci/workflow-scm-step-plugin/pull/53

[JENKINS-65862] exclude asm and common-beanutils from commons-digester3

---

src/test/java/hudson/scm/AbstractSubversionTest.java

This field has been [unused since 1.527](https://github.com/jenkinsci/jenkins/commit/47de54d070f67af95b4fefb6d006a72bb31a5cb8). Setting it is pointless. Stop doing so, so that one day we might be able to actually remove it.
CC @timja

Stop setting `useAntClassLoader` which nothing consumes

---

README.md

The crumb needs to be appended to the headers, not replacing the Content-Type header.
Required for the notification to work on Jenkins LTS 2.277.1 and newer (will throw 500 server error otherwise).
https://issues.jenkins.io/browse/JENKINS-65132
- [X ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [X ] Ensure that the pull request title represents the desired changelog entry
- [X ] Please describe what you did
- [X ] Link to relevant issues in GitHub or Jira
- [X ] Link to relevant pull requests, esp. upstream and downstream changes
- [X ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Update README.md [JENKINS-65132] Fix example script for notifyCommit

---

src/test/java/hudson/scm/listtagsparameter/ListSubversionTagsParameterDefinitionTest.java

Java 8 includes a built-in Base64 decoder, so there is no reason to depend on a third-party library. Using the built-in Java Platform functionality simplifies maintenance.

Drop dependency on Commons Codec

---

pom.xml
src/main/java/hudson/scm/CompareAgainstBaselineCallable.java
src/main/java/hudson/scm/SubversionChangeLogBuilder.java
src/main/java/hudson/scm/SubversionSCM.java
src/main/java/hudson/scm/SubversionTagAction.java
src/main/java/hudson/scm/SubversionWorkspaceSelector.java
src/main/java/hudson/scm/SvnClientManager.java
src/main/java/hudson/scm/UserProvidedCredential.java
src/main/java/hudson/scm/subversion/CheckoutUpdater.java
src/main/java/hudson/scm/subversion/NoopUpdater.java
src/main/java/hudson/scm/subversion/UpdateUpdater.java
src/main/java/hudson/scm/subversion/UpdateWithCleanUpdater.java
src/main/java/hudson/scm/subversion/UpdateWithRevertUpdater.java
src/main/java/hudson/scm/subversion/WorkspaceUpdater.java
src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
src/test/java/hudson/scm/CompareAgainstBaselineCallableTest.java

[JENKINS-48543](https://issues.jenkins.io/browse/JENKINS-48543)
Following up 7d1525edea6641a2febd3f7deeac55c0a89b0d7e to reduce risk and complexity, and provide compatibility with possible future hardenings such as https://github.com/jenkinsci/jenkins/pull/5885. Not tested beyond what automated test coverage exists here.

[JENKINS-48543] Remove agent-to-controller calls

---

src/main/java/hudson/scm/browsers/Phabricator.java

Discovered in https://github.com/jenkinsci/bom/pull/1337. Blocks https://github.com/jenkinsci/plugin-compat-tester/pull/348.
Reproducible in `git-plugin` by adding
```xml
@@ -248,6 +248,11 @@
<artifactId>jenkins-test-harness</artifactId>
<scope>test</scope>
</dependency>
+    <dependency>
+      <groupId>org.jenkins-ci.plugins</groupId>
+      <artifactId>subversion</artifactId>
+      <scope>test</scope>
+    </dependency>
</dependencies>
```
and running `mvn clean verify -Dtest=jenkins.plugins.git.BrowsersJCasCCompatibilityTest#roundTripTest`.
**Note:** These are the _actual_ results with this patch.
The expected result is that the test passes without any exceptions.
The actual result is that the test prints:
```
9.111 [id=1] WARNING …
```

Compatibility with Git plugin

---

pom.xml

[JENKINS-65802] Update SVNKit dependency to 1.10.9, which contains fixes for aarch64 architectures. This should repair blocker issues using current subversion plugin 2.16.0 on M1 macOS machines.

Update SVNKit dependency to 1.10.9

---

pom.xml

Update SVNKit dependency to the just-released 1.10.10, which contains fixes for aarch64 architectures. This should repair blocker issues using current subversion plugin 2.17.0 on M1 macOS machines.
NOTE: This PR is a sequel to https://github.com/jenkinsci/subversion-plugin/pull/276, but should actually resolve the issue. :)
- [x ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ x] Ensure that the pull request title represents the desired changelog entry
- [x ] Please describe what you did
- [x ] Link to relevant issues in GitHub or Jira
- [x ] Link to relevant pull requests, esp. upstream and downstream changes
- [ x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

[JENKINS-65802] Update SVNKit dependency to 1.10.10

---

.mvn/extensions.xml
Jenkinsfile
pom.xml
src/test/java/hudson/scm/SubversionSCMTest.java

This is required for https://github.com/jenkinsci/stapler/pull/452 so that tests continue passing in this plugin and in BOM.

Refresh plugin for April 2023

---

pom.xml
src/main/java/hudson/scm/SubversionSCM.java

Signed-off-by: Olivier Lamy <olamy@apache.org>
```[tasklist]
```

Fix missing dependency on directly used trilead-api

---

pom.xml

See [JENKINS-73281](https://issues.jenkins.io/browse/JENKINS-73281). The `sample-plugin` test in `jenkinsci/bom` started failing on the Jetty 12 EE 8 branch with the stack trace shown in the ticket. The root cause of the problem was unrelated to the Jetty 12 EE 8 upgrade but happened to be exposed by the reshuffled classpath of Jetty 12 EE 8; namely, the Subversion test JAR was pulling in an old version of `mina-sshd-api-common`. Somehow the reshuffled classpath on Jetty 12 EE 8 made this old version take precedence, resulting in the failure:
```
[INFO] +- org.jenkins-ci.plugins:subversion:jar:1256.vee91953217b_6:test
[INFO] |  +- org.tmatesoft.svnkit:svnkit:jar:1.10.10:test
[INFO] |  |  +- org.apache.sshd:sshd-common:jar:2.8.0:test <---- outdated version that causes `InjectedTest` to …
```

[JENKINS-73281] Use `mina-sshd-api` plugin

---

pom.xml

Stop bundling `jna-5.13.0.jar`. `jna-5.14.0.jar` is already bundled by Jenkins core, and its copy of these classes takes precedence.
None

Remove JNA from JPI

---

pom.xml

PCT detected some errors with the last two releases on 2.426.x and earlier, so require 2.440.3 or newer.
CI build

Require 2.440.3 or newer

---

pom.xml

Now that we're on a recent BOM version, this version number is not needed anymore.
`mvn clean verify -Dtest=InjectedTest`

Remove unnecessary version declaration

---

src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
src/main/resources/hudson/scm/subversion/Messages.properties
src/main/resources/hudson/scm/subversion/Messages_de.properties
src/main/resources/hudson/scm/subversion/Messages_es.properties
src/main/resources/hudson/scm/subversion/Messages_fr.properties
src/main/resources/hudson/scm/subversion/Messages_ja.properties
src/main/resources/hudson/scm/subversion/Messages_zh_TW.properties
src/main/resources/jenkins/scm/impl/subversion/SubversionSCMSource/config-detail.jelly
src/main/resources/jenkins/scm/impl/subversion/SubversionSCMSource/resource.js

https://issues.jenkins.io/browse/JENKINS-74013
In Multibranch project select Subversion as a branch source. Fill the Project Repository Base and select credentials.
[Before the change](https://www.youtube.com/watch?v=ty3bmvVWJYo)
[After the change](https://www.youtube.com/watch?v=zBdY7PJSBCQ)

[JENKINS-74013] Extract inline JavaScript event handler from `SubversionSCMSource.java`
