src/main/java/hudson/scm/DirAwareSVNXMLLogHandler.java
src/main/java/hudson/scm/SubversionChangeLogBuilder.java
src/main/java/hudson/scm/SubversionEventHandlerImpl.java
src/main/java/hudson/scm/SubversionSCM.java
src/main/java/hudson/scm/UserProvidedCredential.java
src/main/java/hudson/scm/subversion/UpdateUpdater.java
src/test/java/hudson/scm/SubversionSCMTest.java

Revert a code change which made the System properties `svnkit.http.methods`, and `svnkit.ssh2.persistent ` not get properly set.
@reviewbybees

[FIXED JENKINS-27084] Revert system property change

---

src/main/java/hudson/scm/SubversionTagAction.java

https://issues.jenkins-ci.org/browse/JENKINS-29225

[JENKINS-29225] Failed to tag

---

src/main/java/hudson/scm/SubversionSCM.java

https://issues.jenkins-ci.org/browse/JENKINS-29340

[JENKINS-29340] ISVNAuthentication provider did not provide credentials

---

src/main/java/hudson/scm/subversion/WorkspaceUpdater.java

fix typo:change prefix to suffix

fix typo:change prefix to suffix

---

src/main/java/hudson/scm/SubversionSCM.java
src/test/java/hudson/scm/SubversionEnvVarsTest.java

[JENKINS-31067](https://issues.jenkins-ci.org/browse/JENKINS-31067)

[JENKINS-31067] Global env vars are not available on SVN Polling

---

src/main/java/hudson/scm/SubversionChangeLogBuilder.java
src/main/java/hudson/scm/SubversionSCM.java
src/main/java/hudson/scm/subversion/CheckoutUpdater.java
src/main/java/hudson/scm/subversion/UpdateUpdater.java
src/main/resources/hudson/scm/subversion/Messages.properties

[JENKINS-16711](https://issues.jenkins-ci.org/browse/JENKINS-16711)
As part of this PR, the form validation has been improved and some coding styles reviewed.

[JENKINS-16711] Allow repository URL-encoded

---

src/main/java/hudson/scm/listtagsparameter/ListSubversionTagsParameterDefinition.java

[JENKINS-14155](https://issues.jenkins-ci.org/browse/JENKINS-14155) ([JENKINS-19560](https://issues.jenkins-ci.org/browse/JENKINS-19560) duplicated)
@reviewbybees

[JENKINS-14155] Automatically select the first option of tags listing if default value is not defined

---

pom.xml
src/main/java/hudson/scm/SubversionSCM.java
src/test/java/hudson/scm/SubversionSCMTest.java

findbugs plugin has been updated. 2 errors were solved

---

src/main/java/jenkins/scm/impl/subversion/SVNRepositoryView.java
src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java

A user of `SubversionSCMSource` reported hangs in branch indexing. Thread dumps showed thread activity in locking code, not in SVNKit.
@reviewbybees esp. @recena & @stephenc

Fixes to SVNRepositoryView cache

---

pom.xml
src/main/java/hudson/scm/SubversionSCM.java
src/main/java/hudson/scm/SubversionTagAction.java
src/main/java/hudson/scm/browsers/Sventon.java
src/main/java/hudson/scm/browsers/Sventon2.java
src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java

Analogous to https://github.com/jenkinsci/git-plugin/pull/403.
@reviewbybees

Check EXTENDED_READ, not CONFIGURE, on a context

---

pom.xml
src/test/java/jenkins/scm/impl/subversion/SubversionSampleRepoRule.java
src/test/java/jenkins/scm/impl/subversion/SubversionStepTest.java

Follows up #161.
@reviewbybees

Using SVNKit CLI in preference to native CLI for tests using SubversionSampleRepoRule

---

pom.xml
src/main/java/hudson/scm/SubversionSCM.java
src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
src/main/resources/jenkins/scm/impl/subversion/SubversionSCMSource/config-detail.jelly
src/test/java/jenkins/scm/impl/subversion/SubversionSCMSourceIntegrationTest.java
src/test/java/jenkins/scm/impl/subversion/SubversionSampleRepoRule.java

Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/12; analogous to https://github.com/jenkinsci/git-plugin/pull/433.
Subsumes #164.
@reviewbybees

[JENKINS-31155] Ability to retrieve a single revision

---

pom.xml
src/main/java/hudson/scm/SubversionSCM.java
src/main/java/hudson/scm/SubversionTagAction.java
src/main/java/hudson/scm/browsers/Sventon.java
src/main/java/hudson/scm/browsers/Sventon2.java
src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java

[JENKINS-38048](https://issues.jenkins-ci.org/browse/JENKINS-38048)
Analogue of https://github.com/jenkinsci/git-plugin/pull/437.
@reviewbybees esp. @stephenc

[JENKINS-38048] Permit credentialsId dropdowns to be used from a global configuration screen

---

pom.xml

The right information is placed on the parent POM.

Getting info from the parent POM

---

src/main/java/hudson/scm/CredentialsSVNAuthenticationProviderImpl.java
src/main/java/hudson/scm/SubversionChangeLogBuilder.java
src/main/java/hudson/scm/SubversionSCM.java
src/main/java/hudson/scm/listtagsparameter/ListSubversionTagsParameterDefinition.java
src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
src/main/resources/hudson/scm/subversion/Messages.properties
src/test/java/hudson/scm/CredentialsExternalsTest.java
src/test/java/hudson/scm/PerJobCredentialStoreTest.java
src/test/java/jenkins/scm/impl/subversion/SubversionSampleRepoRule.java

A quick attempt to see if enhanced logging makes [JENKINS-32167](https://issues.jenkins-ci.org/browse/JENKINS-32167) any clearer.
@reviewbybees esp. @stephenc

[JENKINS-32167] Print log messages about which credentials, if any, are being associated with a given realm

---

src/main/java/hudson/scm/browsers/Phabricator.java
src/main/resources/hudson/scm/browsers/Phabricator/config.jelly

This is effectively the same as the Phabriactor component in the git plugin. Seems to work for us.

Phabricator support for the subversion plugin

---

src/main/resources/hudson/scm/SubversionChangeLogSet/digest.jelly
src/main/resources/hudson/scm/SubversionChangeLogSet/index.jelly

Aligns SVN with this change in the ChangeLogParser :
https://github.com/jenkinsci/jenkins/commit/e526809bda3b54f03735979b915f995211915b90

JENKINS-44956: Use browser directly from the changelogset.

---

src/main/java/hudson/scm/SubversionRepositoryStatus.java

Moved try/catch inside the loop to have next ModuleLocation checked if
a SVNCancelExcpetion is raised
Updated error message helping to diagnose which job(s) causes
SVNCancelException(s)

[JENKINS-24802] notifyCommit don't trigger a build

---

src/main/java/hudson/scm/SubversionSCM.java

Corrects a mistake in #198.
@reviewbybees @zionyx

[JENKINS-14541] Mistaken constructor delegation

---

src/main/java/hudson/scm/SubversionEventHandlerImpl.java
src/main/java/hudson/scm/SubversionSCM.java
src/main/java/hudson/scm/subversion/SubversionUpdateEventHandler.java

I missed a binary compatibility issue during the code reviews. We should employ more robots to do that, right? :(
https://issues.jenkins-ci.org/browse/JENKINS-48546
@reviewbybees @jglick

[JENKINS-48546] - Restore the binary compatibility with 2.9

---

pom.xml

SVNKit 1.9.1 passes the unit tests

svnkit 1.9.1

---

pom.xml

Add me to the developer list

---

pom.xml

add a bunch of old developers to the pom file

---

src/main/resources/hudson/scm/browsers/FishEyeSVN/help-url_de.html
src/test/java/hudson/scm/AbstractSubversionTest.java
src/test/java/hudson/scm/CredentialsExternalsTest.java
src/test/java/hudson/scm/DefaultSVNLogFilterTest.java
src/test/java/hudson/scm/SubversionChangeLogSetTest.java
src/test/java/hudson/scm/SubversionRepositoryStatusTest.java
src/test/java/hudson/scm/SubversionSCMChangeLogEntryTest.java
src/test/java/hudson/scm/SubversionSCMTest.java
src/test/java/hudson/scm/SubversionSCMUnitTest.java
src/test/java/hudson/scm/listtagsparameter/ListSubversionTagsParameterDefinitionTest.java
src/test/java/hudson/scm/listtagsparameter/SimpleSVNDirEntryHandlerTest.java
src/test/java/jenkins/scm/impl/subversion/SubversionSCMSourceTest.java
src/test/java/jenkins/scm/impl/subversion/SubversionSampleRepoRule.java

I would like to participate in this plugin and I thought I could start by improving some unit tests. So this is just a very simple pull request to kindly ask if improving the unit tests is a good starting point at all.

Minor enhancements in readability

---

src/main/java/hudson/scm/SubversionSCM.java
src/main/resources/hudson/scm/SubversionSCM/ModuleLocation/config.jelly
src/test/java/jenkins/scm/impl/subversion/SubversionStepTest.java

[JENKINS-50287](https://issues.jenkins-ci.org/browse/JENKINS-50287)
@reviewbybees

[JENKINS-50287] allow to select two different behaviours for as-it-is checkout

---

src/main/resources/hudson/scm/SubversionSCM/config.jelly

Same as https://github.com/jenkinsci/git-plugin/pull/586

[JENKINS-36451] Set scm instance for showing current browser

---

src/main/java/hudson/scm/SubversionChangeLogBuilder.java
src/main/java/hudson/scm/SubversionSCM.java

when calculate change log of externals add module location's credentials as default credentials, fix [JENKINS-45801] and [JENKINS-49219]

[FIX JENKINS-45801] and [FIX JENKINS-49219], when calculate change log of externals, add module location's credentials as default credentials

---

src/main/java/jenkins/scm/impl/subversion/RemotableSVNErrorMessage.java
src/test/java/jenkins/scm/impl/subversion/RemotableSVNErrorMessageTest.java

this PR fixes NPEs thorwn descriped in JENKINS-51817 due to wrong usage of SVNErrorMessage C'tors

JENKINS-51817 fix NPEs

---

pom.xml
src/main/java/jenkins/scm/impl/subversion/RemotableSVNErrorMessage.java
src/test/java/jenkins/scm/impl/subversion/RemotableSVNErrorMessageTest.java

We've been using it for some days without problems and all unit tests pass

SVNKit 1.9.3

---

pom.xml
src/main/java/jenkins/scm/impl/subversion/SubversionSCMFile.java
src/main/java/jenkins/scm/impl/subversion/SubversionSCMFileSystem.java
src/test/java/jenkins/scm/impl/subversion/SubversionSCMFileSystemTest.java
src/test/java/jenkins/scm/impl/subversion/SubversionSampleRepoRule.java

A fork of pull request #221 that should fix the the failing test.
Hopefully this passes and can be merged.
[JENKINS-48420](https://issues.jenkins-ci.org/browse/JENKINS-48420)

[JENKINS-48420] Provide lightweight checkout capability for Subversion

---

src/main/java/jenkins/scm/impl/subversion/SubversionSCMFileSystem.java
src/test/java/jenkins/scm/impl/subversion/SubversionSCMFileSystemBuilderTest.java

[JENKINS-48420](https://issues.jenkins-ci.org/browse/JENKINS-48420)
* New property to disable  lightweight checkout -Djenkins.scm.impl.subversion.SubversionSCMFileSystem.disable=<true/false>
* Test

[JENKINS-48420] Allow disabling  lightweight checkout

---

src/main/java/hudson/scm/SubversionSCM.java
src/test/java/hudson/scm/SubversionSCMTest.java

Allow hyphens in excluded usernames

Hyphenated username

---

src/main/resources/hudson/scm/listtagsparameter/ListSubversionTagsParameterDefinition/help-tagsDir.html

[JENKINS-57468](https://issues.jenkins-ci.org/browse/JENKINS-57468)

[JENKINS-57468] Replace enterCredential w/ credentials

---

Jenkinsfile
pom.xml
src/main/java/jenkins/scm/impl/subversion/SubversionSCMFileSystem.java
src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java

Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/65.

[JENKINS-43802] Implementing retrieve/retrieveRevisions with an Item context

---

src/main/java/hudson/scm/CompareAgainstBaselineCallable.java
src/main/java/hudson/scm/SubversionSCM.java

Solving some problems with externals 
1. same external linked to projekt in different revisions
2. unknown credential for externals on polling
Should also solve: JENKINS-22542

subversion external handling

---

pom.xml
src/main/java/hudson/scm/SubversionChangeLogParser.java
src/main/java/hudson/scm/SubversionChangeLogSet.java

Alternative to #254 + #255 + #257 + #258.

Remove Digester dep

---

src/main/java/hudson/scm/SubversionSCM.java
src/test/java/jenkins/scm/impl/subversion/SubversionStepTest.java

See:
- https://issues.jenkins.io/browse/JENKINS-35176
- https://issues.jenkins.io/browse/JENKINS-38204

[JENKINS-35176] Fixes repeated same "Tag this build" links added to builds.

---

pom.xml
src/main/java/hudson/scm/SubversionSCM.java
src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
src/main/resources/jenkins/scm/impl/subversion/SubversionSCMSource/config-detail.jelly
src/test/java/jenkins/scm/impl/subversion/SubversionSCMSourceIntegrationTest.java
src/test/java/jenkins/scm/impl/subversion/SubversionSCMSourceTest.java

This provides a way to configure a subversion repository browser in a multibranch project.
See https://issues.jenkins.io/browse/JENKINS-66777

[JENKINS-66777] Added SubversionSCMSource repository browser support

---

src/test/java/hudson/scm/SubversionSCMTest.java
src/test/java/jenkins/scm/impl/subversion/SubversionSCMSourceIntegrationTest.java

Configuration Round-trip Testing explained in https://www.jenkins.io/doc/developer/testing/#configuration-round-trip-testing

Simplify tests with "config round-trip" pattern

---

src/main/java/hudson/scm/SubversionSCM.java
src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
src/main/resources/jenkins/scm/impl/subversion/SubversionSCMSource/config-detail.jelly
src/test/java/jenkins/scm/impl/subversion/SubversionSCMSourceIntegrationTest.java
src/test/java/jenkins/scm/impl/subversion/SubversionSCMSourceTest.java

Allow configuring the `WorkspaceUpdater` to use in multibranch jobs.
See https://issues.jenkins.io/browse/JENKINS-41850

[JENKINS-41850] Add SubversionSCMSource workspaceUpdater support

---

src/main/java/hudson/scm/SubversionTagAction.java
src/main/resources/hudson/scm/SubversionSCM/DescriptorImpl/enterCredential.jelly

Preparation for core sunsetting dated icons: https://github.com/jenkinsci/jenkins/pull/5778
@didiez Would be nice if you can also trigger a release after merging this PR.
Thanks in advance!

chore: Prepare for sunset icon removal from core

---

pom.xml

`mvn test`
built the plugin locally to inspect the hpi `WEB-INF\lib` to check `eddsa.jar` is no longer bundled.

use eddsa-api plugin for eddsa library

---

pom.xml
src/test/java/pipeline/LibraryAdderSubversionTest.java
src/test/java/pipeline/ReadTrustedStepSubversionTest.java
src/test/java/pipeline/SCMBinderSubversionTest.java
src/test/java/pipeline/SCMSourceRetrieverSubversionTest.java

Extracted from https://github.com/jenkinsci/workflow-multibranch-plugin/pull/314 + https://github.com/jenkinsci/pipeline-groovy-lib-plugin/pull/135.

Moved Pipeline tests

---

pom.xml

https://github.com/jenkinsci/subversion-plugin/pull/306#discussion_r1707041250

Update to 2.462.1

---

src/test/java/pipeline/CpsScmFlowDefinitionSubversionTest.java

Like #306 but now for https://github.com/jenkinsci/workflow-cps-plugin/pull/922.

Moved `checkoutDirectoriesAreNotReusedByDifferentScms` test
